Kitenest/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kitenest.Data;
using Kitenest.Models;
using Microsoft.AspNetCore.Authorization;

namespace Kitenest.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CitiesController : Controller
    {
        private readonly KitenestDbContext _context;

        public CitiesController(KitenestDbContext context)
        {
            _context = context;
        }

        // GET: Cities
        public async Task<IActionResult> Index()
        {
            return View(await _context.City.ToListAsync());
        }

        // GET: Cities/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.City
                .FirstOrDefaultAsync(m => m.Id == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // GET: Cities/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] City city)
        {
            if (ModelState.IsValid)
            {
                _context.Add(city);
                await _context.SaveChangesAsync();
                return RedirectToAction("manageSchools", "Admin");
            }
            return View(city);
        }

        // GET: Cities/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.City.FindAsync(id);
            if (city == null)
            {
                return NotFound();
            }
            return View(city);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] City city)
        {
            if (id != city.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(city);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CityExists(city.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("manageSchools", "Admin");
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var city = await _context.City
                .FirstOrDefaultAsync(m => m.Id == id);
            if (city == null)
            {
                return NotFound();
            }

            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var city = await _context.City.FindAsync(id);
            _context.City.Remove(city);
            await _context.SaveChangesAsync();
            return RedirectToAction("manageSchools", "Admin");
        }

        private bool CityExists(int id)
        {
            return _context.City.Any(e => e.Id == id);
        }
    }
}

Kitenest/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kitenest.Data;
using Kitenest.Models;
using Microsoft.AspNetCore.Authorization;

namespace Kitenest.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CountriesController : Controller
    {
        private readonly KitenestDbContext _context;

        public CountriesController(KitenestDbContext context)
        {
            _context = context;
        }

        // GET: Countries
        public async Task<IActionResult> Index()
        {
            return View(await _context.Country.ToListAsync());
        }

        // GET: Countries/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country
                .FirstOrDefaultAsync(m => m.Id == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // GET: Countries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Countries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Country country)
        {
            if (ModelState.IsValid)
            {
                _context.Add(country);
                await _context.SaveChangesAsync();
                return RedirectToAction("manageSchools", "Admin");
            }
            return View(country);
        }

        // GET: Countries/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country.FindAsync(id);
            if (country == null)
            {
                return NotFound();
            }
            return View(country);
        }

        // POST: Countries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Country country)
        {
            if (id != country.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(country);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CountryExists(country.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("manageSchools", "Admin");
            }
            return View(country);
        }

        // GET: Countries/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var country = await _context.Country
                .FirstOrDefaultAsync(m => m.Id == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }

        // POST: Countries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var country = await _context.Country.FindAsync(id);
            _context.Country.Remove(country);
            await _context.SaveChangesAsync();
            return RedirectToAction("manageSchools", "Admin");
        }

        private bool CountryExists(int id)
        {
            return _context.Country.Any(e => e.Id == id);
        }
    }
}

Kitenest/Controllers/SchoolsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kitenest.Data;
using Kitenest.Models;
using Kitenest.Models.Interfaces;
using System.Collections.Generic;
using Kitenest.Validators;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using Microsoft.AspNetCore.Authorization;
using Kitenest.ViewModels;

namespace Kitenest.Controllers
{
    //[Authorize(Roles = "Admin")]
    [AllowAnonymous]
    public class SchoolsController : Controller
    {
        public int pageSize = 10;
        private readonly KitenestDbContext _context;

        public SchoolsController(KitenestDbContext context)
        {
            _context = context;
        }


        // GET: Schools
        public async Task<IActionResult> Index()
        {
            var kitenestDbContext = _context.School.Include(s => s.City).Include(s => s.Continent);
            return View(await kitenestDbContext.ToListAsync());
        }

        // GET: Schools/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var school = await _context.School
                .Include(s => s.City)
                .Include(s => s.Continent)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (school == null)
            {
                return NotFound();
            }

            return View(school);
        }

        // GET: Schools/Create

        public IActionResult Create()
        {
            ViewBag.Continents = new SelectList(_context.Continent.ToList(), "Id", "Name");
            ViewBag.Cities = new SelectList(_context.City.ToList(), "Id", "Name");

            return View();
        }

        // POST: Schools/Create
        [HttpPost]
        [ValidateAntiForgeryToken]        
        public async Task<IActionResult> Create([Bind("Id,Name,Mobile,Continent_id,Country,City_id")] School school)
        {               
            
            if (ModelState.IsValid )
            {
                _context.Add(school);
                await _context.SaveChangesAsync();
                return RedirectToAction("manageSchools", "Admin");
            }

            ViewBag.Continents = new SelectList(_context.Continent.ToList(), "Id", "Name");
            ViewBag.Cities = new SelectList(_context.City.ToList(), "Id", "Name");
            return View();
        }

        // GET: Schools/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var school = await _context.School.FindAsync(id);
            if (school == null)
            {
                return NotFound();
            }

            
            ViewBag.Continents = new SelectList(_context.Continent.ToList(), "Id", "Name");
            ViewBag.Cities = new SelectList(_context.City.ToList(), "Id", "Name");
            
            return View(school);
        }

        // POST: Schools/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Mobile,Continent_id,Country,City_id")] School school)
        {
            if (id != school.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(school);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolExists(school.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Continents = new SelectList(_context.Continent.ToList(), "Id", "Name");
            ViewBag.Cities = new SelectList(_context.City.ToList(), "Id", "Name");
            return View(school);
        }

        // GET: Schools/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var school = await _context.School
                .Include(s => s.City)
                .Include(s => s.Continent)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (school == null)
            {
                return NotFound();
            }

            return View(school);
        }

        // POST: Schools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var school = await _context.School.FindAsync(id);
            _context.School.Remove(school);
            await _context.SaveChangesAsync();
            return RedirectToAction("manageSchools", "Admin");
        }

        private bool SchoolExists(int id)
        {
            return _context.School.Any(e => e.Id == id);
        }


        public IActionResult Search()
        {
            return View();
        }

        [HttpGet]
        [AllowAnonymous] 
        [Route("Search")]
        public async Task<IActionResult> SearchSchools(string schoolName, string continent, string country,
            string city, [FromQuery]int page = 1)
        {

            SchoolsViewModel schoolsList = new SchoolsViewModel();

            var query = _context.School
                .Include(e => e.City)
                .Include(e => e.Continent);

            var resultQuery = query.Where(e =>
                ((string.IsNullOrEmpty(schoolName) ? e.Id > 0 : e.Name.Contains(schoolName)) &&
                (string.IsNullOrEmpty(continent) ? e.Id > 0 : e.Continent.Name.Contains(continent)) &&
                (string.IsNullOrEmpty(city) ? e.Id > 0 : e.City.Name.Contains(city)) &&
                (string.IsNullOrEmpty(country) ? e.Id > 0 : e.Country.Contains(country))) )
                .ToList();

            var limitedResult = resultQuery
                .Skip((page - 1) * pageSize)
                .Take(pageSize);



            schoolsList.Schools = limitedResult;
            schoolsList.CurrentPage = page;
            schoolsList.TotalPages = (resultQuery.Count() / pageSize);

            return View(schoolsList);
      
        }
    }
}

Kitenest/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Admin Panel</h2>


<div class="row">
    <div class="col-md-4 col-md-offset-3">
        <p><a class="btn btn-lg btn-info" asp-controller="Admin" asp-action="manageSchools">Schools Stuff</a></p>
    </div>
    <div class="col-md-4">
        <p><a class="btn btn-lg btn-info" asp-controller="Admin" asp-action="manageUsers">Manage Users</a></p>
    </div>
</div>

Kitenest/Views/Admin/_CitiesPartial.cshtml
@model IEnumerable<Kitenest.Models.City>


<table class="table">
    
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-controller="Cities" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-controller="Cities" asp-route-id="@item.Id" style="color:red">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Kitenest/Views/Admin/_ContinentsPartial.cshtml
@model IEnumerable<Kitenest.Models.Continent>


<table class="table">
    
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-controller="Continents" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-controller="Continents" asp-route-id="@item.Id" style="color:red">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Kitenest/Views/Admin/_CountriesPartial.cshtml
@model IEnumerable<Kitenest.Models.Country>


<table class="table">
    
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-controller="Countries" asp-route-id="@item.Id">Edit</a> |

                <a asp-action="Delete" asp-controller="Countries" asp-route-id="@item.Id" style="color:red">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Kitenest/Views/Admin/_RolesPartial.cshtml
<h4>Roles list</h4>

<a asp-action="Create" asp-controller="Admin">Create New</a>
    <table class="table table-striped table-hover col-sm-6 col-lg-6 col-md-6 ">
        @foreach (var role in ViewBag.Roles)
        {
            <tr>
                <td class="col-sm-1 col-lg-4 col-md-4">
                    <strong>@role.Text </strong>
                </td>
                <td class="col-sm-1 col-lg-2 col-md-2">
                    <span onclick="return confirm('Do you really want to delete that role ?')"><a href="/Roles/Delete?RoleName=@role.Text" class="delLink" style="color:red;">Delete</a></span> |
                    @Html.ActionLink("Edit", "Edit", new { roleName = @role.Text })
                </td>
            </tr>
        }
    </table>

Kitenest/Views/Admin/_SchoolsPartial.cshtml
@model IEnumerable<Kitenest.Models.School>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mobile)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Continent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mobile)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Continent.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-controller="Schools" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-controller="Schools" asp-route-id="@item.Id" style="color:red">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Kitenest/Views/Admin/_UsersPartial.cshtml
<h4>Users list</h4>

<a asp-action="Create" asp-controller="Admin">Create New</a>
<table class="table table-striped table-hover col-sm-6 col-lg-6 col-md-6 ">
    @foreach (var user in ViewBag.Users)
    {
        <tr>
            <td class="col-sm-1 col-lg-4 col-md-4">
                <strong>@user.Text </strong>
            </td>
            <td class="col-sm-1 col-lg-2 col-md-2">
                <span onclick="return confirm('Do you really want to delete that user?')"><a href="/Roles/Delete?RoleName=@user.Text" class="delLink" style="color:red;">Delete</a></span> |
                @Html.ActionLink("Edit", "Edit", new { roleName = @user.Text })
            </td>
        </tr>
    }
</table>

Kitenest/Views/Admin/manageSchools.cshtml
@using Kitenest.ViewModels
@model WorldViewModel


<body>
    <div class="row">
        <div class="col-md-8">
            <h3><b>Schools</b></h3>
            <p>
                <a asp-action="Create" asp-controller="Schools">Create New</a>
            </p>
            @Html.Partial("~/Views/Admin/_SchoolsPartial.cshtml", Model.Schools.ToList())
        </div>
    </div>
    <br /><br />
    <div class="col-md-4">
        <h3><b>Continents</b></h3>
        <p>
            <a asp-action="Create" asp-controller="Continents">Create New</a>

        </p>
        @Html.Partial("~/Views/Admin/_ContinentsPartial.cshtml", Model.Continents.ToList())
    </div>

    <div class="col-md-4">
        <h3><b>Countries</b></h3>
        <p>
            <a asp-action="Create" asp-controller="Countries">Create New</a>
        </p>
        @Html.Partial("~/Views/Admin/_CountriesPartial.cshtml", Model.Countries.ToList())
    </div>

    <div class="col-md-4">
        <h3><b>Cities</b></h3>
        <p>
            <a asp-action="Create" asp-controller="Cities">Create New</a>
        </p>
        @Html.Partial("~/Views/Admin/_CitiesPartial.cshtml", Model.Cities.ToList())
    </div>


</body>

Kitenest/Views/Admin/manageUsers.cshtml
@{
    ViewData["Title"] = "manageUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Manage Users, Roles and Access</h2>

<div class="row">
    <div class="col-md-4">
        <partial name="~/Views/Admin/_RolesPartial.cshtml" />
    </div>
    <div class="col-md-4">
        <partial name="~/Views/Admin/_UsersPartial.cshtml" />
    </div>
</div>